name: .NET

on:
  push:
    paths:
      - 'src/**'
  
  pull_request:
    paths:
      - 'src/**'
  
  workflow_dispatch:

jobs:
  test-infrastructure:
    name: Infrastructure
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/Infrastructure

      - name: Build
        run: dotnet build --no-restore
        working-directory: src/Infrastructure

      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: src/Infrastructure

  test-service-identity:
    name: Service.Identity
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/Service.Identity

      - name: Build
        run: dotnet build --no-restore
        working-directory: src/Service.Identity

      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: src/Service.Identity

  test-service-tenants:
    name: Service.Tenants
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/Service.Tenants

      - name: Build
        run: dotnet build --no-restore
        working-directory: src/Service.Tenants

      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: src/Service.Tenants
